=== Karalynx/internet-technologies/mini/mini_6.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="Online">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Taip"/>
            <xs:enumeration value="Ne"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Kaina">
        <xs:restriction base="xs:string">
          <xs:pattern value="\d+(\.\d{1,2})?($|€|£|¥)"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="Žaidimas">
        <xs:sequence>
            <xs:element name="pavadinimas" type="xs:string"/>
            <xs:element name="stilius" type="xs:string"/>
            <xs:element name="online" type="Online"/>
            <xs:element name="kaina" type="Kaina"/>
        </xs:sequence>
        <xs:attribute name="steam_id" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:element name="žaidimų_parduotuvė">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="žaidimas" type="Žaidimas" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>

        <xs:key name="steam_id">
            <xs:selector xpath="žaidimas"/>
            <xs:field xpath="@steam_id"/>
        </xs:key>
    </xs:element>
</xs:schema>

=== Karalynx/internet-technologies/mini/mini_6.xml
<žaidimų_parduotuvė xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mini_6.xsd">
    <žaidimas steam_id="7581546580">
        <pavadinimas>Zombiai</pavadinimas>
        <stilius>Šaudyklė</stilius>
        <online>Taip</online>
        <kaina>25$</kaina>
    </žaidimas>
    <žaidimas steam_id="6539688821">
        <pavadinimas>Mario Kart</pavadinimas>
        <stilius>Lenktynės</stilius>
        <online>Taip</online>
        <kaina>49.99€</kaina>
    </žaidimas>
    <žaidimas steam_id="5672834321">
        <pavadinimas>Minecraft</pavadinimas>
        <stilius>Išlikimas</stilius>
        <online>Ne</online>
        <kaina>40.0$</kaina>
    </žaidimas>
</žaidimų_parduotuvė>
